---
title: Introduction to GIS - Exercise Syllabus

format: tud-beamer
---

Please read carefully the following syllabus and try to come prepared to the first lecture.

The goal of the exercise part of this course is to complement your knowledge of empirical literature in empirical spatial economics with hand-on experience with geo-data wrangling and analysis. The focus of the course is on presenting different aspects of working with geo-data in R, in giving you the tools to leverage your econometrics knowledge and make statistical inference using highly spatial accurate images.

# Introduction to GIS Course Syllabus

**Evaluation**

After attending the 6 exercise classes you are expected to produce an empirical coding project using geo-data using what you have learned in the coding exercises. This project should have a focus on the data wrangling more than on the econometric strategy but you are welcome to touch upon any socio-economic topic of interest for you. There are no strict deadlines before the end of the course, but you are warmly invited to marta.bernardi\@tu-dresden.de a research proposal with the outlook of your project at any point in the semester up to two weeks before the deadline and I will give you feedback on it.

More information on how exactly this project should look like when you submit it will be given in the classes. You are allowed to work in group of maximum 2 people and it should be clear which part is being carried on by who.

**References**

The course is mostly based on :

-   <https://github.com/sebastianhohmann/gis_course>

-   <https://r.geocompx.org/>

-   <https://tmieno2.github.io/R-as-GIS-for-Economists/>

And during the 6 classes we will work with data from the Dresden Open data Portal and from Open Street maps, but we will also speak about geo-data sources in general and where to find data on other parts of the world.

## Part 1 - Setting up GIS in R (90 mins)

### A) Best practices in R projects

Before coming to this first exercise class, you are expected to have tried to:

1.  Create a GitHub account
2.  Create a Private folder in GitHub called Intro_to_GIS
3.  Have R Studio and GIT installed on your personal computer
4.  Have created an R Project and linked it to the GitHub folder you created

If you have any problem with the previous 4 steps, please feel free to email me and/or come to the first lecture 45 to 30 minutes early, and I will be trying to help you fix the setup technical issues that you are encountering.

During the first part of this lecture, a generic introduction on how to set up a healthy collaborative project will be presented. This is a fundamental part of working with geo-data in R and in R in general. At the end of the course, you are expected to share with us the link to your GitHub folder that we should be able to run without any further tweaking. Failing to do so will be translated into a significant lower evaluation. If you would like a more detailed explanation on this you are warmly advised to visit the introductory class of the empirical research task seminar where an entire 90 minutes is dedicated to setting up git projects and R best practices.

B\) Types of Geo-Data and leading R packages to work with them

C\) Projections, Coordinates and weird geo-acronyms

D\) Making basic maps in R using ggplot

## Part 2 - Geo-Data sources and Geo-data packages-types combinations (90 mins)

A\) Where to Download geo-data and how to load them in the project space

B\) Points, Lines, Vectors, and how to mix them up

C\) Rasters data types, what is a grid?

D\) Different packages for different approaches

## Part 3 - Basic Spatial operations (90 mins)

A\) Vector to vector operations \[join, intersect\]

B\) Raster to raster operations \[overlay\]

C\) Vector-Raster operations \[crop, reproject\]

D\) Raster-Vector and Vector-Raster conversions

## Part 4 - Making cute maps using multiple types of geo-data (90 mins)

A\) Maps parts and features

B\) Vector maps with geom_sf

C\) Raster maps with geom_raster

D\) Interactive maps using tmap

## Part 5 - Multiple rasters structures and stars (90 mins)

A\) Raster bricks and stacks

B\) Multiple rasters operations

C\) Stars and when to use them

D\) Stars operations

## Part 6 - Econometric Inference with geo-data (90 mins)

A\) Administrative levels and geo-data workflows

B\) When to get rid of the coordinates

C\) Conley errors and clustering for spatial autocorrelation

D\) Q&A time on the final project
